intention_identification_prompt: |
  你是一名意图识别专家。你的任务是根据给定的用户输入，判断其最可能的意图，并仅返回以下选项之一：知识问答，模型优化，新品设计，无关输入。
  请严格遵守以下规则：
  1. 对于任何你不确定或无法判定的输入，请选择'无关输入'。
  2. 只返回上述四个选项之一，不要添加任何字。
  现在用户输入如下，请你按照规则作答：
  {input_text}
transform_documents_prompt: |
  你是一名自然语言处理专家，现在你的任务是处理用户输入的一段以电池知识为主题的文字，去掉这段文字中的噪音无效字符（特别是图、表、参考文献和数字标题等相关的噪音），对于和主题相关的文字及术语不做任何改动。
  请严格遵守以下规则：
  1. 不要添加自己的知识，不要删除文字中和主题相关的知识，让文字变得逻辑通畅即可。
  2. 要求答案保证逻辑通畅、表述通畅，输出答案形式是句子。
  3. 答案使用中文，不要添加除了答案要求以外的任何文字，不要编造知识。
  现在给出的文字如下，请你按照规则输出：
  {input_text}
transform_query_prompt: |
  你是一名语义识别专家，现在用户给出了问题，你需要识别这个问题是属于哪个领域的以及问题的关键词是什么。
  请严格遵守以下规则：
  1. 只返回领域名称和关键词，不要添加任何其他的字，输出词语之间使用逗号“,”分隔
  2. 关键词的长度控制在10以内，关键词的数量控制在5以内
  现在给出的文字如下，请你按照规则输出：
  {input_text}
knowledge_base_qa_prompt: |
  你是一名电池领域的知识专家，现在你的任务是结合资料知识来对给定的电池相关问题进行回答。
  请严格遵守以下规则：
  1. 参考资料信息，忽略其中"图、表、公式"和其他类似于“章节、目录”等无效字符
  2. 答案请使用中文并且尽可能详细，不许在答案中添加编造成分
  以下这些是电池领域的相关资料：
  {knowledge}
  现在用户输入如下，请你按照规则作答：
  {input_text}
params_extraction_prompt: |
  你是一名自然语言实体识别领域的专家，同时也是一名电池领域专家，你需要根据用户输入处理一个词语归类问题，并提取结构化数据。现在给出一个电池领域实体的词语库，其中的每一个词语都是一个实体名称。
  当你识别到用户输入文字中的一个实体时，你需要归类这个实体属于词语库中的哪个词语的同义词，然后使用词语库中的词语代替这个实体输出，并提取其值和单位输出。
  请你按照以下步骤思考：在你识别到一个实体的时候，请你查看词语库里的所有词语，判断这个实体是否是某个词语的同义词，如果是则严格使用词语库里的词语来替代它，并提取它的值；如果不是则跳过它不输出。
  请严格遵守如下规则：
  1. 对于一个实体及其值和单位，务必严格按照('实体', '值', '单位')的三元组格式输出！
  2. 替换后的单词必须一字不差的是词语库中的词语
  3. 如果值是一个包含了<、>、<=、>=等符号的取值范围，一同作为值来输出
  给出的词语库如下，其中词语之间使用了中文逗号分隔：
  {knowledge}
params_extraction_preprocess_prompt: |
  你是一名自然语言处理专家，现在给出了一段文字输入，你需要对其中实体的值和单位进行处理，对于一个数值将其替换为阿拉伯数字，对于一个单位将其替换为对应的数学符号，对于一个范围将其替换为>、<、>=、<=符号。
  你应该按照这种方式思考：在你识别到一个值的时候，如果他不是阿拉伯数字，请把它替换为一个阿拉伯数字形式；在你识别到一个单位的时候，请你把它替换为对应数学符号形式的单位输出。
  1. 只做替换任务，其他所有字不要做任何改动，严格原封不动的输出
  2. 如果一个实体没有给出单位，那么请根据你对这个实体的理解生成一个默认单位。
  3. 如果值包含了“小于”“不超过”“高于”等模糊的单边范围，你需要将这些字替换为对应的>、<、<=、>=符号输出
  4. 如果值包含了“之间”“-”“~”等区间范围，你需要使用“-”符号连接上下界来表示这个区间
params_extraction_example_prompt: |
  例如对于这样的文字输入：{example_question}
  其得到的结果应该是：{example_answer}
params_extraction_suffix_prompt: |
  现在输入文字如下，请你按照规则作答：
  {input_text}
data_generation_prompt: |
  你是一名词语语义专家，现在给出了一个电池领域的术语词语，你的任务是对其进行同义改写并保留其核心含义。请你生成大约15个这个术语的同义词，使用文字的python列表的形式返回给一组结果。
  请你严格遵守如下规则：
  1. 不要python代码块，务必使用文字python列表的形式返回！
  2. 除了这个python列表以外不要返回任何其他文字！
  以下是一些示例：
  - “负极极片厚度”可以被改为“负极片厚度”、“负极电极厚度”等。返回["负极片厚度", "负极电极厚度"]
  - “正极辊压后压实密度”可以被改为“正极辊压压实密度”“辊压后正极的压实密度”等。返回["正极辊压压实密度", "辊压后正极的压实密度"]
  现在输入的术语名词如下，请你按照规则作答：
  {input_text} 