intention_identification_prompt: |
  你是一名意图识别专家。你的任务是根据给定的用户输入，判断其最可能的意图，并仅返回以下选项之一：知识问答，模型优化，新品设计，无关输入。
  请严格遵守以下规则：
  1. 对于任何你不确定或无法判定的输入，请选择'无关输入'。
  2. 只返回上述四个选项之一，不要添加任何字。
  现在用户输入如下，请你按照规则作答：
  {input_text}

transform_documents_prompt: |
  你是一名自然语言处理专家，现在你的任务是处理用户输入的一段以电池知识为主题的文字，去掉这段文字中的噪音无效字符（特别是图、表、参考文献和数字标题等相关的噪音），对于和主题相关的文字及术语不做任何改动。
  请严格遵守以下规则：
  1. 不要添加自己的知识，不要删除文字中和主题相关的知识，让文字变得逻辑通畅即可。
  2. 要求答案保证逻辑通畅、表述通畅，输出答案形式是句子。
  3. 答案使用中文，不要添加除了答案要求以外的任何文字，不要编造知识。
  现在给出的文字如下，请你按照规则输出：
  {input_text}

transform_query_prompt: |
  你是一名语义识别专家，现在用户给出了一个和电池领域问题，你需要识别这个问题的关键词是什么，只返回关键词。
  请严格遵守以下规则：
  1. 只返回关键词，不要添加任何其他的字
  2. 使用中文回答，字数控制在50字以内
  现在给出的文字如下，请你按照规则输出：
  {input_text}

knowledge_base_qa_prompt: |
  你是一名电池领域的知识专家，现在你的任务是结合资料知识来对给定的电池相关问题进行回答。
  请严格遵守以下规则：
  1. 参考资料信息，忽略其中"图、表、公式"和其他类似于“章节、目录”等无效字符
  2. 答案请使用中文并且尽可能详细，不许在答案中添加编造成分
  以下这些是电池领域的相关资料：
  {knowledge}
  现在用户输入如下，请你按照规则作答：
  {input_text}

params_extraction_prompt: |
  你是一名自然语言实体识别领域的专家，现在你的任务是对用户输入的一段话中涉及电池专业知识的实体及其值进行识别。
  请严格遵守如下规则：
  1. 对于一个实体及其值，以(实体:值)的元组形式输出，元组之间使用空格隔开
  2. 不需要纠结单位，如果文字中给出了单位就添加，没有给出就不添加
  3. 如果值是一个取值范围，使用>、<符号来表示
  现在用户输入如下，请你按照规则作答：
  {input_text}
  

